feat(file)!: deploymennt test40
BREAKING CHANGE: deployment test40

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,22 +14,54 @@ on:
 jobs:
   version-and-tag:
     runs-on: frontend
+    if: github.ref == 'refs/heads/main'
     outputs:
-      new_tag: ${{ steps.get-version.outputs.version }}
-
+      new_tag: ${{ steps.tag.outputs.new_tag }}
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: Read version from file
-        id: get-version
-        run: |
-          VERSION=$(cat version.txt)
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
-      - name: Show version
+      - name: Fetch all tags and check existing tags
         run: |
-          echo "Deploying version: ${{ steps.get-version.outputs.version }}"
+          git fetch --tags
+          echo "Existing tags:"
+          git tag || true
+
+      - name: Ensure at least one initial tag exists
+        run: |
+          git fetch --tags
+          if [ -z "$(git tag)" ]; then
+            echo "No tags found. Creating v0.0.0..."
+            git tag v0.0.0
+            git push origin v0.0.0
+          else
+            echo "Tags already exist."
+          fi
+
+      - name: Bump and Tag Version (semantic versioning)
+        id: tag
+        uses: mathieudutour/github-tag-action@v6.2
+        with:
+          github_token: ${{ secrets.PAT_TOKEN }}
+          release_branches: main
+          default_bump: false
+          tag_prefix: "v"
+          fetch_all_tags: true
+          custom_release_rules: |
+            feat:minor
+            fix:patch
+            chore:patch
+            docs:patch
+            refactor:patch
+            BREAKING CHANGE:major
+
+      - name: Validate new tag value
+        if: ${{ steps.tag.outputs.new_tag == '' }}
+        run: |
+          echo "No new tag generated — likely no matching commit message or missing commits."
+          exit 1
+
+      - name: Show New Tag
+        run: echo "New version is ${{ steps.tag.outputs.new_tag }}"
 
   docker-build-push:
     runs-on: frontend
@@ -240,4 +272,4 @@ jobs:
           body: |
             New release: ${{ needs.version-and-tag.outputs.new_tag }}
         env:
-          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} "
